### ISSUE TITLE
Register

### ISSUE THREAD

**Issue by Andi-Code** [Kappathic/SEII-Instaclone#2]
# Story
Ich als User will mich mit meiner Bild (Optional), Name,  E-Mail und Password Registrieren können. 

# Akzeptanz Kriterien 
- [x] E-Mail eingeben können
- [x] Bild hochladen
- [x] Name eingeben können
- [x] Password eingeben können
- [x] Password 2x eingeben
- [x] Fehlermeldung falls Password falsch ist  
- [x] Account ist bereits vorhanden Anzeigen

# Umsetzung
* Route zum Senden der Registrieungs Daten (POST-Request als JSON)
* JSON Fehlermeldung als Antwort
* Statuscode 200 für erfolg
* Bild mit im Request senden

**Comment by cschilling00** [comment]
Registration wurde in #14 abgeschlossen, Profilbild wird seperaten Endpunkt  /user/updateProfilePic hochgeladen
