### ISSUE TITLE
Get the Posts for the Main Feed from Backend & Display them in Frontend

### ISSUE THREAD

**Issue by Kappathic** [Kappathic/SEII-Instaclone#56]
User: I want to see the posts of all the people I am following displayed on my Main Feed in chronological order.

**Comment by cschilling00** [comment]
To get all posts of people that I follow perform a get request to /api/post/feed
![image](https://user-images.githubusercontent.com/37246071/115589145-cca18700-a2cf-11eb-953b-573978b38768.png)
