### ISSUE TITLE
Get the posts from my own account and display them on my profile

### ISSUE THREAD

**Issue by Kappathic** [Kappathic/SEII-Instaclone#57]
User: I want to be able to see all my own posts on my profile page in chronological order.

**Comment by cschilling00** [comment]
To get my own post create a get request to/api/user/profile/username
for chronological order creationdate is needed: #62 
![image](https://user-images.githubusercontent.com/37246071/115588773-61f04b80-a2cf-11eb-966d-5a9805b334d8.png)
