### ISSUE TITLE
Login Connection to Backend

### ISSUE THREAD

**Issue by Kappathic** [Kappathic/SEII-Instaclone#58]
User: I want to be able to log-in to my account & have a session cookie safe my current data.

**Comment by cschilling00** [comment]
To login do a post request to /api/auth/login the backend returns the user and sets a http only cookie which is inaccessible by the frontend
![image](https://user-images.githubusercontent.com/37246071/115587934-839d0300-a2ce-11eb-80dc-2dc69bd35e03.png)
