### ISSUE TITLE
Creating a post

### ISSUE THREAD

**Issue by Kappathic** [Kappathic/SEII-Instaclone#60]
User: I want to be able to post a new picture to the platform, including a description & hashtags.

**Comment by cschilling00** [comment]
to post a new post, create a post request to /api/post 
![image](https://user-images.githubusercontent.com/37246071/115587037-80edde00-a2cd-11eb-8534-517c5cf49496.png)

**Comment by cschilling00** [comment]
To get the base64: [stackoverflow](https://stackoverflow.com/questions/24289182/how-to-strip-type-from-javascript-filereader-base64-string)
